# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that definitions somehow override complete default configuration
    App\Repository\UserRepository:
        class: App\Repository\UserRepository
    App\Repository\PostRepository:
        class: App\Repository\PostRepository
    App\Repository\PostLikeRepository:
        class: App\Repository\PostLikeRepository
    App\Repository\CommentRepository:
        class: App\Repository\CommentRepository
    App\Repository\CommentLikeRepository:
        class: App\Repository\CommentLikeRepository
    App\Repository\FriendshipRepository:
        class: App\Repository\FriendshipRepository
    App\Repository\ChatRepository:
        class: App\Repository\ChatRepository
    App\Repository\MessageRepository:
        class: App\Repository\MessageRepository
    App\Repository\PostPictureRepository:
        class: App\Repository\PostPictureRepository
    App\Repository\RatingRepository:
        class: App\Repository\RatingRepository

    # Adicion치mos este reposit칩rio (est치 correto)
    App\Repository\FollowRepository:
        class: App\Repository\FollowRepository

    App\Security\Authentication\AuthenticationSuccessHandler:
        arguments:
            # Esta linha est치 correta
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
            # A linha extra do $userRepository foi REMOVIDA daqui.
